### PR TITLE
Fix ARCH_SUFFIX issue on fetch-release

### LINKED ISSUE #4: Failed to install Swift 5.8 on Ubuntu22.04 aarch64
The download link now is wrong and will get a 404 Not Found response
```
https://download.swift.org/swift-5.8-release/ubuntu2204/swift-5.8-RELEASE/swift-5.8-RELEASE-ubuntu22.04-aarch64.tar.gz
```

The correct link is the following (According to https://www.swift.org/download/)
```
https://download.swift.org/swift-5.8-release/ubuntu2204-aarch64/swift-5.8-RELEASE/swift-5.8-RELEASE-ubuntu22.04-aarch64.tar.gz
```

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Close #4

### CODE REVIEW

**Review by stevapple — APPROVED** [review]
Thanks for the quick fix! Can you extract `$SWIFT_DOWNLOAD_SITE/$1/$SYSTEM_NAME${SYSTEM_VERSION//./}$ARCH_SUFFIX` to a new function, to ensure we don’t make such mistake again?

**Comment by Kyle-Ye** [comment]
> Thanks for the quick fix! Can you extract `$SWIFT_DOWNLOAD_SITE/$1/$SYSTEM_NAME${SYSTEM_VERSION//./}$ARCH_SUFFIX` to a new function, to ensure we don’t make such mistake again?

No problem. Also I forgot to bump the version.🤣 Would you mind me bumping the version to 0.13.2 or 0.14?

**Comment by stevapple** [comment]
> Also I forgot to bump the version.🤣 Would you mind me bumping the version to 0.13.2 or 0.14?

0.13.2 is okay I think:) There's no breaking UI/UX change.

**Comment by Kyle-Ye** [comment]
> Thanks for the quick fix! Can you extract `$SWIFT_DOWNLOAD_SITE/$1/$SYSTEM_NAME${SYSTEM_VERSION//./}$ARCH_SUFFIX` to a new function, to ensure we don’t make such mistake again?

I'm not very familiar with Bash commands. Could you help provide some hints on how to call a function in a string context on bash?
```bash
## Download link helper

download-link-helper() {
    return $SWIFT_DOWNLOAD_SITE/$1/$SYSTEM_NAME${SYSTEM_VERSION//./}$ARCH_SUFFIX
}

local DOWNLOAD_URL="$SWIFT_DOWNLOAD_SITE/swift-$NEW_VERSION-release/$SYSTEM_NAME${SYSTEM_VERSION//./}$ARCH_SUFFIX/swift-$NEW_VERSION-RELEASE/swift-$NEW_VERSION-RELEASE-$SYSTEM_NAME$SYSTEM_VERSION$ARCH_SUFFIX.tar.gz"
=>
local DOWNLOAD_URL= download-link-helper swift-$NEW_VERSION-release + "/swift-$NEW_VERSION-RELEASE/swift-$NEW_VERSION-RELEASE-$SYSTEM_NAME$SYSTEM_VERSION$ARCH_SUFFIX.tar.gz" // ❌
```

**Comment by stevapple** [comment]
IMO this should be:
```bash
download-base() {
    echo "$SWIFT_DOWNLOAD_SITE/$1/$SYSTEM_NAME${SYSTEM_VERSION//./}$ARCH_SUFFIX"
}

local DOWNLOAD_URL=`download-base swift-$NEW_VERSION-release`/swift-$NEW_VERSION-RELEASE/swift-$NEW_VERSION-RELEASE-$SYSTEM_NAME$SYSTEM_VERSION$ARCH_SUFFIX.tar.gz
```

Strings are flowing everywhere in a shell script🤣 You just need to dump it and embed the output into another string.

**Comment by Kyle-Ye** [comment]
Test it locally with the following and everything seems OK.
```
./swiftbox.sh check 5.8
./swiftbox.sh check nightly
./swiftbox.sh get 5.8
./swiftbox.sh get nightly
```

**Review by stevapple — APPROVED** [review]
Thanks!

**Pull request merged**
